### ISSUE TITLE
Turbolinks prevents correct link-jumping when clicking on AnchorJS links containing unicode text.

### ISSUE THREAD

**Issue by Fdango** [bryanbraun/anchorjs#108] opened 2019-04-08 10:13 UTC
This is my demo.
https://fdango.github.io/bookT/intro.html

**Comment by bryanbraun** [comment] 2019-05-19 22:44
Hey, I'm just looking into this now.

I can reproduce the jumping behavior you're describing... I can see it happening in Chrome, Safari, and Firefox.

Fortunately, the link added to the URL bar works fine. If you click the anchor link, and copy the updated url, and browse to that page, it'll still jump to the right place. Still that jump on the initial click is annoying.

I'm not sure how anchorjs could be causing since it just uses plain links... there's no listeners or anything. That makes me think it's a browser issue, but we'll need to do more digging.

Some things we can try:
- Testing other languages / alphabets to see if we can isolate which characters it's happening for.
- See if the characters have any encoding happening in the HTML that could be affecting things.

**Comment by Fdango** [comment] 2019-05-20 07:22
@bryanbraun yeah，This problem has been plagued for a long time，I have not found a solution

**Comment by bryanbraun** [comment] 2019-08-05 05:28
@Fdango, I did a bunch of testing and now I understand the gist of what's happening here.

**The problem:**

Your webpages are built with [Jupyter Book](https://github.com/jupyter/jupyter-book), which is using a javascript library called [Turbolinks](https://github.com/turbolinks/turbolinks) for fast page transitions.

Turbolinks is interfering with the natural behavior of these anchor links by reloading the whole page when you click one. There's an [issue in the turbolinks repo to prevent these reloads](https://github.com/turbolinks/turbolinks/issues/75), but at the time of this post, it hasn't been fixed.

**A workaround solution:**

You can fix the problem by disabling turbolinks on jump-links like those created by AnchorJS. You can do this with `preventDefault` ([as described in this comment](https://github.com/turbolinks/turbolinks/issues/75#issuecomment-244915109)), or by [adding an attribute of `data-turbolinks="false"`](https://github.com/turbolinks/turbolinks#disabling-turbolinks-on-specific-links) to all the jump-links, like this (for example):

```js
document.querySelectorAll('.anchorjs-link').forEach((link) => {
  link.setAttribute('data-turbolinks', false);
});
```

**Open questions:**

* *Why did English AnchorJS links work, but not ones with Chinese characters?* I don't know. I did learn that this affected all links with unicode characters in them. For example, `#test-发展历史` and `#test-അടിത്തട്ടിലെ` and `#test-Заголовок1` were all having issues, whereas ASCII text links like `#test-abc123` were working fine. We'd probably have to dig into the internals of Turbolinks to isolate the cause here.
* *Is there a way to get AnchorJS to work with Turbolinks?* Probably. There are a lot of ways to implement Turbolinks, and I suspect the bug was a result of the way Jupyter Book implemented it. You could probably [create an issue on the Jupyter Book repo](https://github.com/jupyter/jupyter-book/issues/new) and figure out a different implementation that doesn't produce this side-effect.

***

Note: I'm going to rename this issue to more accurately describe the problem.

**Comment by Fdango** [comment] 2019-08-06 03:12
@bryanbraun thanks，

**Comment by bryanbraun** [comment] 2019-10-12 04:08
I'm going to close this issue for now, since I see no further action needed in this project. 👍

**Closed by bryanbraun** 2019-10-12 04:08 UTC
