### ISSUE TITLE
Documentation is not available

### ISSUE THREAD

**Issue by mrkkrp** [bryanbraun/anchorjs#88] opened 2017-06-01 07:11 UTC
http://www.bryanbraun.com/anchorjs#examples

**Comment by bryanbraun** [comment] 2017-06-02 15:02
Hi @mrkkrp. 👋  What exactly is the problem you're finding? I'm able to see documentation/examples at that link. 😕

**Comment by mrkkrp** [comment] 2017-06-02 15:42
That's weird, here is what I see:

![anchorjs-docs](https://cloud.githubusercontent.com/assets/8165792/26733327/2ea267d8-47c3-11e7-9d64-9af33c251f75.png)

**Comment by mrkkrp** [comment] 2017-06-02 16:14
If you believe that it does not affect other users, feel free to close the issue. I've read the docs from the repo itself locally.

**Comment by thecotne** [comment] 2017-06-02 16:37
Link works for me ...

**Comment by bryanbraun** [comment] 2017-06-02 19:50
Anybody else having trouble seeing this?

**Comment by bryanbraun** [comment] 2017-06-14 13:41
Closing since we haven't been able to reproduce the issue. Please re-open if anybody else sees it or has more details.

**Closed by bryanbraun** 2017-06-14 13:41 UTC

**Comment by mrkkrp** [comment] 2017-06-14 13:58
FTR, it works for me now!
